### ISSUE TITLE
Need appropriate loader to handle this .node, in Electron.

### ISSUE THREAD

**Issue by linonetwo** [yanyiwu/nodejieba#101]
I'm in Mac, installing nodejieba to https://github.com/chentsulin/electron-react-boilerplate , require nodejieba and get this error.

node-loader did no help for this.

**Comment by linonetwo** [comment]
Similar to https://github.com/yanyiwu/nodejieba/issues/91

**Comment by linonetwo** [comment]
Tried node-loader, and got ```Module did not self-register```

**Comment by linonetwo** [comment]
npm rebuild causing
```
nodejieba.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

**Comment by linonetwo** [comment]
```rm -rf ./node_modules && yarn``` don't work for me

**Comment by linonetwo** [comment]
After funning ```./node_modules/.bin/electron-rebuild``` , error back to ```Module did not self-register```

**Comment by yanyiwu** [comment]
i am not familiar with electron, so i am unable to help this issue . sorry

**Comment by wm123450405** [comment]
移除源码中  lib/utils.h 文件中 对 node.h 文件的引用

**Comment by linonetwo** [comment]
@wm123450405 厉害了，你怎么发现的？
