### ISSUE TITLE
無法載入包含中文的字典路徑

### ISSUE THREAD

**Issue by Augus** [yanyiwu/nodejieba#102]
無法載入中文路徑字典，載入路徑若包含中文 `nodejieba` 會立即崩潰，有辦法處理嗎? 

測試環境: Windows
問題重現方式: 隨意建立一個 node 專案，以中文命名專案文件夾，並安裝 nodejieba。

![image](https://user-images.githubusercontent.com/1012267/32417434-aed25fe8-c294-11e7-830f-13229977c267.png)

**Comment by yanyiwu** [comment]
这个比较麻烦，我没有windows环境可以去处理。只能用户自己探索了。
