### ISSUE TITLE
支持繁体？

### ISSUE THREAD

**Issue by kenianbei** [yanyiwu/nodejieba#104]
`console.log(nodejieba.cut('妈妈')); // [ '妈妈' ]`
`console.log(nodejieba.cut('媽媽')); // [ '媽', '媽' ]`

**Comment by bubao** [comment]
你需要繁体字字典，我这里有[user.dict](https://github.com/bubao/jieba_demo/raw/master/dict/user.dict)，把这个字典加载到默认字典的位置。

**Comment by kenianbei** [comment]
謝謝... 我其實是已經用[opencc](https://github.com/BYVoid/OpenCC)把jieba.dict.utf8換成繁體的。
