### ISSUE TITLE
好像不能选择模式吧？大佬你还更新吗？

### ISSUE THREAD

**Issue by bubao** [yanyiwu/nodejieba#105]
之前用过python的jieba，是可以选择分词模式的，这个不能选择，导致我需要tag的时候，百分比被切开了
```json
[{"word":"2","tag":"x"},{"word":"%","tag":"x"}]
```
而且数字的tag也是`x`

**Comment by yanyiwu** [comment]
https://github.com/yanyiwu/nodejieba/blob/master/test/demo.js
有cut和cutHMM和cutAll等模式。
