### ISSUE TITLE
调用cut方法的bug

### ISSUE THREAD

**Issue by jiazhengwen** [yanyiwu/nodejieba#106]
使用官方的demo

var nodejieba = require('nodejieba');
var sentence = "我是拖拉机学院手扶拖拉机专业的。不用多久，我就会升职加薪，当上CEO，走上人生巅峰。";
console.log(nodejieba.cut(sentence));
console.log(nodejieba.cut(sentence, undefined));
console.log(nodejieba.cut(sentence, null));
console.log(nodejieba.cut(sentence, 11));
console.log(nodejieba.cut(sentence, false));
console.log(nodejieba.cut(sentence, true));

后面5种调用返回结果一样。

**Comment by yanyiwu** [comment]
这不算bug吧？只是对参数异常没处理完善，所以尽量不要用异常参数去试了，用标准用法吧，参考：https://github.com/yanyiwu/nodejieba/blob/master/test/demo.js
