### ISSUE TITLE
在 electron 里面用，好像不支持 node 57？

### ISSUE THREAD

**Issue by i7soft** [yanyiwu/nodejieba#107]
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`)

**Comment by phodal** [comment]
```
yarn add electron-rebuild --dev
./node_modules/.bin/electron-rebuild -p -t "dev,prod,optional"
```
