### ISSUE TITLE
“我对电影的爱”，这句话词性分析，最后一个爱，在 Python 版本是名词，在 nodejs 是动词

### ISSUE THREAD

**Issue by i7soft** [yanyiwu/nodejieba#108]
“我对电影的爱”，这句话词性分析，最后一个爱，在 Python 版本是名词，在 nodejs 是动词

**Comment by yanyiwu** [comment]
Nodejieba对词性分析支持的不完善，如果对词性分析有需求的，建议使用jieba分词
