### ISSUE TITLE
在线demo里面的分词具体方法

### ISSUE THREAD

**Issue by stonehank** [yanyiwu/nodejieba#124]
我尝试了test/demo.js里面所有的分词命令，都分不到我想要的，但是在线demo里却可以，请问下在线demo里的分词命令是如何的

**Comment by crapthings** [comment]
会不会是词库的问题哦 @stonehank

**Comment by stonehank** [comment]
> 会不会是词库的问题哦 @stonehank

有可能，我用的是默认的，里面就一个`红掌拨清波`...live-demo不是默认词库吗

**Comment by stonehank** [comment]
@crapthings 
加到自定义词典里面确实可以，请问下有没有现成的词典库提供的？主要是前端术语方面的，感谢你的帮助！

**Comment by crapthings** [comment]
@stonehank 领域词库还是要整理积累的吧，我看好像没有太好的办法都是人肉弄。

**Comment by stonehank** [comment]
了解:thumbsup:
