### ISSUE TITLE
windows安装错误

### ISSUE THREAD

**Issue by zgmqdl** [yanyiwu/nodejieba#131]
![image](https://user-images.githubusercontent.com/35328737/56082206-7b40a080-5e48-11e9-93a6-295a9d91b262.png)

**Comment by salamander-mh** [comment]
我也是这个错误

**Comment by Brooooooklyn** [comment]
试一下 [@node-rs/jieba](https://github.com/Brooooooklyn/node-rs/tree/master/packages/jieba)
