### ISSUE TITLE
无法上传至小程序云函数

### ISSUE THREAD

**Issue by Tony091250147** [yanyiwu/nodejieba#136]
由于需要本地编译生成/build/Release/nodejieba.node，所以上传至小程序云函数的时候会报错‘invalid elf header‘。有什么办法可以绕开这个限制？

**Comment by LisenH** [comment]
同问，楼主解决了吗？

**Comment by linshushi** [comment]
貌似现在上传小程序云函数还是有报这个错误， @wang-jun-coder 用的是2.5.2，确定这个问题解决了吗？
