### ISSUE TITLE
Won't compile on Node.js v10.16.3 (LTS)

### ISSUE THREAD

**Issue by binarykitchen** [yanyiwu/nodejieba#138]
Try to install this package using Node.js v10.16.3. It will fail with this error

```
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
```

Similar to https://github.com/nodejs/nan/issues/763

Maybe consider bumping some of your packages such as nan?

**Comment by yanyiwu** [comment]
can you use v12 with npm > 6 ?
for example: https://travis-ci.org/yanyiwu/nodejieba/jobs/542785432 it compile succeed.

**Comment by binarykitchen** [comment]
I could but can't use v12 in my project.

**Comment by yanyiwu** [comment]
so can you use npm 5 for your node v10

**Comment by videmort** [comment]
Same error here trying to install local-npm package
Fails also with node 12
https://www.npmjs.com/package/local-npm

**Comment by Brooooooklyn** [comment]
Try [@node-rs/jieba](https://github.com/Brooooooklyn/node-rs/tree/master/packages/jieba)
