### ISSUE TITLE
Nodejieba with browserify

### ISSUE THREAD

**Issue by TaihouKai** [yanyiwu/nodejieba#150]
您好

我想用browserify在chrome extension里使用nodejieba，但是我发现浏览器似乎不支持stream：
```
if (stream._handle && stream.isTTY && typeof stream._handle.setBlocking === 'function') {
```
这行里的_handle会报错：
`TypeError: Cannot read property '_handle' of undefined`

请问除了我自己重新写一遍这个repo里涉及stream的部分，有什么解决办法吗？

**Comment by citasionm** [comment]
@TaihouKai Did you find a solution to the problem? I have the exact same issue.

**Comment by TaihouKai** [comment]
> @TaihouKai Did you find a solution to the problem? I have the exact same issue.

Sorry, I  it has been too long since then. However, according to my memory, I probably gave up at last...

**Comment by citasionm** [comment]
I wish I could but lunr.zh from lunr-languages has nodejieba as a dependency. I opened a ticket at browserify as well to see if there is a parameter that I can use to solve this.
