### ISSUE TITLE
win10安装失败，node 12.16.1

### ISSUE THREAD

**Issue by ioechain** [yanyiwu/nodejieba#154]
已安装windows-build-tools、node-gyp且无报错，装了vs2019
报错信息如下

C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment>npm install nodejieba --save

> nodejieba@2.4.1 install C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodejieba@2.4.1 and node@12.16.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  index.cpp
  nodejieba.cpp
  win_delay_load_hook.cc
C:\Users\marry\AppData\Local\node-gyp\Cache\12.16.1\x64\node.lib : fatal error LNK1107: 文件无效或损坏: 无法在 0x395C76 处读取 [C:\U
sers\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba\build\nodejieba.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\marry\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marry\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\marry\\WeChatProjects\\youfu\\cloudfunctions\\segment\\node_modules\\nodejieba\\build\\Release\\nodejieba.node" "--module_name=nodejieba" "--module_path=C:\\Users\\marry\\WeChatProjects\\youfu\\cloudfunctions\\segment\\node_modules\\nodejieba\\build\\Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\marry\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba\build\Release\nodejieba.node --module_name=nodejieba --module_path=C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba\build\Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marry\\WeChatProjects\\youfu\\cloudfunctions\\segment\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\marry\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba\build\Release\nodejieba.node --module_name=nodejieba --module_path=C:\Users\marry\WeChatProjects\youfu\cloudfunctions\segment\node_modules\nodejieba\build\Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN segment@1.0.0 No description
npm WARN segment@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejieba@2.4.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marry\AppData\Roaming\npm-cache\_logs\2020-03-16T08_29_13_319Z-debug.log

错误日志文件：链接：https://pan.baidu.com/s/1xm-L57Wn6HGFMmu8M_qBdA 
提取码：dqth

反复尝试多次基本都是这样报错，希望能有有效回复

**Comment by weituotian** [comment]
我也是啊
```
node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz

```

**Comment by johnsmith0209** [comment]
+1 同报了`404`

```
node-pre-gyp http 404 https://github.com/yanyiwu/nodejieba/releases/download/2.4.0/nodejieba-v2.4.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.0/nodejieba-v2.4.0-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodejieba@2.4.0 and node@12.16.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/yanyiwu/nodejieba/releases/download/2.4.0/nodejieba-v2.4.0-node-v72-darwin-x64.tar.gz
```

**Comment by Brooooooklyn** [comment]
试一下 [@node-rs/jieba](https://github.com/Brooooooklyn/node-rs/tree/master/packages/jieba)

**Comment by ZeroSimple** [comment]
我也是

**Comment by coffiner** [comment]
> 我也是啊
> 
> ```
> node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> node-pre-gyp http 404 https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> ```

node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-win32-x64.tar.gz

用这个
node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/archive/v2.4.1.tar.gz

**Comment by coffiner** [comment]
> > 我也是啊
> > ```
> > node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> > node-pre-gyp http 404 https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> > node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> > ```
> 
> node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-win32-x64.tar.gz
> 
> 用这个
> node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/archive/v2.4.1.tar.gz

https://github.com/yanyiwu/nodejieba/issues/154

**Comment by Hivol** [comment]
> > 我也是啊
> > ```
> > node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> > node-pre-gyp http 404 https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> > node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v64-win32-x64.tar.gz
> > ```
> 
> node-pre-gyp WARN Tried to download(404): [`2.4.1` nodejieba-v2.4.1-node-v72-win32-x64.tar.gz (download)](https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-win32-x64.tar.gz)
> 
> 用这个
> node-pre-gyp http GET [`v2.4.1`.tar.gz](https://github.com/yanyiwu/nodejieba/archive/v2.4.1.tar.gz)

我已成功解决这个问题了。下载 [https://github.com/yanyiwu/nodejieba/archive/v2.4.1.tar.gz](https://github.com/yanyiwu/nodejieba/archive/v2.4.1.tar.gz) 这个压缩包解压后重命名为 "nodejieba"，手动放入项目的 node_modules 目录中。最后再执行一次 `yarn` 或者 `npm install` 即可

**Comment by wiidede** [comment]
（并不是很好的做法）可以强行
`npm install nodejieba`
给你的项目装个最新版的nodejieba🤪

**Comment by weituotian** [comment]
好~(￣▽￣)~*
