### ISSUE TITLE
v0.2.8在 `npm publish` 的时候有误操作，请使用 v0.2.9。

### ISSUE THREAD

**Issue by yanyiwu** [yanyiwu/nodejieba#16]
v0.2.8在 `npm publish` 的时候有误操作，
导致在 `npm install nodejieba` 的时候会报错。
已被弃用。
请使用 v0.2.9。

**Comment by gengdaoping** [comment]
v0.2.9安装失败  那个直接在github上下载的缺少build文件夹啊

**Comment by gengdaoping** [comment]
![image](https://cloud.githubusercontent.com/assets/6937502/6643394/d0f44d24-c9e6-11e4-8063-3b68cb1bae6c.png)
这是什么原因

**Comment by yanyiwu** [comment]
Windows的支持是 @hho2002 开发的。
@hho2002  Windows我不熟，你能帮忙看一下吗？

**Comment by hho2002** [comment]
使用 node-gyp 编译需要 Python (v2.7.3 recommended, v3.x.x is not supported)

https://github.com/TooTallNate/node-gyp

**Comment by hho2002** [comment]
编译环境
* node 0.10.36
* node-gyp 1.0.2
* python 2.7.8
* Visual Studio C++ 2010 express

![2015-03-14_161257](https://cloud.githubusercontent.com/assets/680019/6650905/67a45dbc-ca65-11e4-8bf4-ef577a0e2d08.png)
