### ISSUE TITLE
服务器挂了吗？怎么安装失败

### ISSUE THREAD

**Issue by Ruoyu-Klaus** [yanyiwu/nodejieba#166]
node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for nodejieba@2.4.1 and node@12.13.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/yanyiwu/nodejieba/releases/download/2.4.1/nodejieba-v2.4.1-node-v72-darwin-x64.tar.gz

**Comment by Ruoyu-Klaus** [comment]
是我node-gyp没安好

**Comment by civerzhang** [comment]
请问，node-gyp是要重装吗？我的node-gyp是node-sass带的
node-gyp@3.8.0
nodejieba@2.5.1
node@10.16.0
