### ISSUE TITLE
增加多instances方法

### ISSUE THREAD

**Issue by kanasimi** [yanyiwu/nodejieba#170]
例如在繁簡轉換程序中，需要隨時轉換不同辭典。若每次都需要重新載入辭典，將造成額外的浪費。

**Comment by yanyiwu** [comment]
听起来似乎合理。不过还是想确认下，可以把简体和繁体词典合并成一个辞典么？


发自我的iPhone

**Comment by kanasimi** [comment]
現在暫時採用合併辭典的方法 但是需要繁複的計算 也不真的準確
https://github.com/kanasimi/Chinese_converter/blob/master/_build/generate_dictionary.js#L111
https://github.com/kanasimi/Chinese_converter/blob/master/dictionaries/commons.txt
會有相同詞彙在不同詞典中 權重不同的問題
有些實在不同的語境(台灣 香港 中國大陸)權重不同 甚至連詞性標記都不同

**Comment by yanyiwu** [comment]
好的明白了，我抽空看下是否好改吧。

发自我的iPhone
