### ISSUE TITLE
在nw.js下ERROR:nw_shell.cc(335)] Error: Module did not self-register.

### ISSUE THREAD

**Issue by Jayin** [yanyiwu/nodejieba#18]
![7bcf2850-c20c-42ee-a243-02e4723004c9](https://cloud.githubusercontent.com/assets/2763894/6863304/f4d31a74-d489-11e4-9294-819c6fcad503.jpg)

是nw.js问题还是？

**Comment by yanyiwu** [comment]
nw_shell.cc 是干啥的？
看上去不像是nodejieba的问题啊。

**Comment by Jayin** [comment]
[nw.js](https://github.com/nwjs/nw.js) -> node webkit

**Comment by Jayin** [comment]
我也怀疑是nw.js的问题 我先去那边提个issue

**Comment by iwege** [comment]
如果是native module，必须要用nw-gyp重新编译一次。

**Comment by Jayin** [comment]
√ get
