### ISSUE TITLE
安装失败../lib/nodejieba.h:8:37: error: expected template-name before ‘<’ token

### ISSUE THREAD

**Issue by xiaoyuit** [yanyiwu/nodejieba#183]
安装时出现如下错误，请问这个可能是哪里出问题了？

> 错误图片地址
> https://s3.ax1x.com/2020/12/10/riPfUK.jpg

**Comment by janckerchen** [comment]
npm  run  rebuild 遇到同样问题 
macOS Catalina  10.15.7
![2020-12-24_10-46-53 (24)](https://user-images.githubusercontent.com/68181/103055724-0094c600-45d6-11eb-99fc-739bbd1f753b.png)

**Comment by 4haohansen2033** [comment]
这个问题有人解决了吗？

**Comment by tsvico** [comment]
node版本太低
我用`js_native_api.h.patch` 解决了此问题
```patch
21c21
< #define NAPI_VERSION 6
---
> #define NAPI_VERSION 5
481c481
< // #ifdef NAPI_EXPERIMENTAL
---
> #ifdef NAPI_EXPERIMENTAL
525c525
< // #endif  // NAPI_EXPERIMENTAL
---
> #endif  // NAPI_EXPERIMENTAL
```
执行 `patch -R ~/.electron-gyp/10.1.0/include/node/js_native_api.h js_native_api.h.patch`

仅供参考
