### ISSUE TITLE
libstdc++.so.6: version `CXXABI_1.3.9' not found 

### ISSUE THREAD

**Issue by as17744** [yanyiwu/nodejieba#186]
编译阶段报错libstdc++.so.6: version `CXXABI_1.3.9' not found 
![image](https://user-images.githubusercontent.com/28487513/103621825-c251bc00-4f70-11eb-8ddf-1920255e63ab.png)

**Comment by TrumanGu** [comment]
same here

**Comment by cyjake** [comment]
`string /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI` 看一下系统支持的版本

**Comment by hjiog** [comment]
![image](https://user-images.githubusercontent.com/42141272/127131534-073f07e4-dfd3-49c2-9780-5e33bab7637e.png)

如何安装1.3.9？

**Comment by cyjake** [comment]
切换到更新版本的 gcc 即可，如果是 centos 的话，可以试试更新 devtoolset

**Comment by hjiog** [comment]
贴一个debian的解决方案https://blog.csdn.net/weixin_43189735/article/details/104719493
