### ISSUE TITLE
No License. It is recommended to add a license.

### ISSUE THREAD

**Issue by StevenMichael3213** [yanyiwu/nodejieba#189]
License can protects the copyright and makes it easy for others to use.

Can I modify the source code and distribute at will？

**Comment by yanyiwu** [comment]
MIT License.
![image](https://user-images.githubusercontent.com/2162645/112468253-fb950d80-8da2-11eb-8a3c-b21a3aed255d.png)

**Comment by McShelby** [comment]
Maybe the author means the official github license marker?

![grafik](https://user-images.githubusercontent.com/11670870/112675736-cd2d3600-8e67-11eb-8433-d3ba34182001.png)


https://saraford.net/2017/02/17/how-to-add-a-license-to-a-repo-and-have-it-be-recognized-for-an-existing-github-repo-048/

**Comment by StevenMichael3213** [comment]
> Maybe the author means the official github license marker?
> 
> ![grafik](https://user-images.githubusercontent.com/11670870/112675736-cd2d3600-8e67-11eb-8433-d3ba34182001.png)
> 
> https://saraford.net/2017/02/17/how-to-add-a-license-to-a-repo-and-have-it-be-recognized-for-an-existing-github-repo-048/

Yes, It will be better if add a license file.

**Comment by yanyiwu** [comment]
ok. good point. thank you. @McShelby 
https://github.com/yanyiwu/nodejieba/pull/190
