### ISSUE TITLE
nodejs 0.12 下不可用了

### ISSUE THREAD

**Issue by dofy** [yanyiwu/nodejieba#19]
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Seven/works/qlist/base/node_modules/nodejieba/index.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by yanyiwu** [comment]
好的我今天找时间查看看。

**Comment by yanyiwu** [comment]
我这边使用 node v0.12.1 一切正常啊。
```
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.1 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/yanyiwu/code/nodejieba/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/yanyiwu/.node-gyp/0.12.1/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/yanyiwu/.node-gyp/0.12.1',
gyp info spawn args   '-Dmodule_root_dir=/home/yanyiwu/code/nodejieba',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/yanyiwu/code/nodejieba/build'
  CXX(target) Release/obj.target/segment/src/segment.o
  CXX(target) Release/obj.target/segment/src/mix_segment.o
  CXX(target) Release/obj.target/segment/src/query_segment.o
  CXX(target) Release/obj.target/segment/src/pos_tagger.o
  CXX(target) Release/obj.target/segment/src/keyword_extractor.o
  SOLINK_MODULE(target) Release/obj.target/segment.node
  SOLINK_MODULE(target) Release/obj.target/segment.node: Finished
  COPY Release/segment.node
make: Leaving directory `/home/yanyiwu/code/nodejieba/build'
gyp info ok
```

你是不是 `git clone`  下来之后没有 `npm install`，导致一些依赖包没有安装？

**Comment by dofy** [comment]
安装没问题 运行时报错 错误我贴出来了

/**
 * Seven Yu
 * TEL: +86 136 0123 6077
 * Twitter: @dofy
 */

~EOF~

**Comment by yanyiwu** [comment]
但是我这边运行一切正常啊。
你那边能正常运行 `npm test` 命令吗？
或者能否贴一下你的运行代码，否则不好判断。

**Comment by dofy** [comment]
好 我再试试



/**
 * Seven Yu ( Dofy )
 * Co-Founder of qdan.me
 * Tel: +86 136 0123 6077
 * Twitter: @dofy
 * Github: @dofy
 * */

EOF

2015-04-09 18:17 GMT+08:00 Yanyi Wu <notifications@github.com>:

**Comment by dofy** [comment]
您收到了邀请！

在Airbnb，您可以挖掘世界各地的当地房东出租的独特房源。


2015年6月27日前注册即可为您的第一趟¥ 9,219或以上的旅程节省¥ 4,917。





接受邀请
http://zh.airbnb.com/c/b6a57a?eluid=0&euid=4c2d1f72-69d8-9448-a148-234d917f0f4d&ri=21692452&s=1

谢谢！
Airbnb团队

P.O. Box 410807, San Francisco, CA 94121

取消订阅
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwNTQwODViMzlmYmU4YjQwZTVmYTU3MTVhMTk0NjM5N2M1ZjQ2ZWU0YTYxN2E4OTJjZjAwMDAwMDAxMTEzZTEzYTk5MmExNjljZTA0MDAxNTEzQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiI0YzJkMWY3Mi02OWQ4LTk0NDgtYTE0OC0yMzRkOTE3ZjBmNGQifQ==&mac=ttGIvlApt67uI4rWcePmZZnZIAM=

### Airbnb ###

**Comment by dofy** [comment]
您收到了邀请！

在Airbnb，您可以挖掘世界各地的当地房东出租的独特房源。


2015年6月27日前注册即可为您的第一趟¥ 9,219或以上的旅程节省¥ 4,917。





接受邀请
http://zh.airbnb.com/c/b6a57a?eluid=0&euid=315be505-731e-b84a-dffa-dd82765622a4&ri=21692453&s=1

谢谢！
Airbnb团队

P.O. Box 410807, San Francisco, CA 94121

取消订阅
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwNTQwODU2M2M1YTdmN2IyMjI0Mjc4ZjQ3MjE4NjA3MDBjMWMzMDdlZGM1NmFlOTJjZjAwMDAwMDAxMTEzZTBjZGU5MmExNjljZTA0MDAxNTEzQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiIzMTViZTUwNS03MzFlLWI4NGEtZGZmYS1kZDgyNzY1NjIyYTQifQ==&mac=yX-pP4IX_vYR8rGl37iMypzbS9c=

### Airbnb ###

**Comment by yanyiwu** [comment]
@dofy 怎么回事？
