### ISSUE TITLE
能否提供一下 arm64 版本

### ISSUE THREAD

**Issue by hewen** [yanyiwu/nodejieba#199]
MacBook下M1版本编译出错， 能否提供一下 arm64 版本？

`node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v83-darwin-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@14.17.6 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v83-darwin-arm64.tar.gz`

**Comment by ttaccp** [comment]
关注中

**Comment by myalgo** [comment]
How did you fix it ?

**Comment by yangsamuellu** [comment]
How did you fix it ?

**Comment by yanyiwu** [comment]
Could you please tell me which version you are using?
