### ISSUE TITLE
安装 v2.6.0 安装失败

### ISSUE THREAD

**Issue by Yunkou** [yanyiwu/nodejieba#205]
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz

这个包没打 路径是 404

**Comment by yanyiwu** [comment]
嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。

发自我的iPhone

**Comment by AkagiYui** [comment]
> 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone
> […](#)
> 在 2022年1月10日，18:37，yun.kou ***@***.***> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

使用v2.5.2版本无法使用最新LTS版本node v16,

**Comment by wz2cool** [comment]
我自己解决了也是强制安全 2.5.2   npm install nodejieba@2.5.2

**Comment by hotoo** [comment]
@yanyiwu 这个什么时候能解决呀？我这边要锁死依赖吗？

**Comment by Fucntion** [comment]
> > 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone
> > […](#)
> > 在 2022年1月10日，18:37，yun.kou _**@**_.***> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
> 
> 使用v2.5.2版本无法使用最新LTS版本node v16,

我把node切换到14.19.0，然后锁死"nodejieba": "2.5.2"，亲测可用。

**Comment by TechQuery** [comment]
> 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone
> […](#)
> 在 2022年1月10日，18:37，yun.kou ***@***.***> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

@yanyiwu 改用 GitHub actions 吧，很香，我也可以抽空发个 PR

**Comment by yanyiwu** [comment]
尝试转到github action，但是探索了下配置没配置上。。。还没搞动nodejs这些怎么跑通。如果有pr能帮忙就太感谢了。

发自我的iPhone

**Comment by Giftia** [comment]
> 尝试转到github action，但是探索了下配置没配置上。。。还没搞动nodejs这些怎么跑通。如果有pr能帮忙就太感谢了。 发自我的iPhone
> […](#)
> 在 2022年6月3日，17:33，South Drifted ***@***.***> 写道： ﻿ 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone … 在 2022年1月10日，18:37，yun.kou @.***> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. @yanyiwu 改用 GitHub actions 吧，很香，我也可以抽空发个 PR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

#212 `npm ci` 需要 `package-lock.json`，补上之后 action 就可以跑通

**Comment by robertIsaac** [comment]
> > 尝试转到github action，但是探索了下配置没配置上。。。还没搞动nodejs这些怎么跑通。如果有pr能帮忙就太感谢了。 发自我的iPhone
> > […](#)
> > 在 2022年6月3日，17:33，South Drifted _**@**_._**> 写道： ﻿ 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone … 在 2022年1月10日，18:37，yun.kou @.**_> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. @yanyiwu 改用 GitHub actions 吧，很香，我也可以抽空发个 PR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.
> 
> #212 `npm ci` 需要 `package-lock.json`，补上之后 action 就可以跑通

@Giftia when do expect it to be fixed?

**Comment by Giftia** [comment]
> > > 尝试转到github action，但是探索了下配置没配置上。。。还没搞动nodejs这些怎么跑通。如果有pr能帮忙就太感谢了。 发自我的iPhone
> > > […](#)
> > > 在 2022年6月3日，17:33，South Drifted _**@**_._**> 写道： ﻿ 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone … 在 2022年1月10日，18:37，yun.kou @.**_> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. @yanyiwu 改用 GitHub actions 吧，很香，我也可以抽空发个 PR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.
> > 
> > 
> > #212 `npm ci` 需要 `package-lock.json`，补上之后 action 就可以跑通
> 
> @Giftia when do expect it to be fixed?

thanks for your contribution, but the maintainer is too busy at his work and life to fix that now, so it's still pending

**Comment by yanyiwu** [comment]
> > 尝试转到github action，但是探索了下配置没配置上。。。还没搞动nodejs这些怎么跑通。如果有pr能帮忙就太感谢了。 发自我的iPhone
> > […](#)
> > 在 2022年6月3日，17:33，South Drifted _**@**_._**> 写道： ﻿ 嗯 2.6.0 travis-ci 发布出问题了，travis-ci 变成收费项目了。建议先用 v2.5.2 版本吧。 发自我的iPhone … 在 2022年1月10日，18:37，yun.kou @.**_> 写道： ﻿ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-linux-x64.tar.gz 这个包没打 路径是 404 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. @yanyiwu 改用 GitHub actions 吧，很香，我也可以抽空发个 PR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.
> 
> #212 `npm ci` 需要 `package-lock.json`，补上之后 action 就可以跑通

我看已经merge了，是需要npm发布个新版本后才

**Comment by Jedliu** [comment]
Looking forward to the fix! Thank you!

**Comment by robertIsaac** [comment]
> This issue has not been updated for over 1 year and will be marked as stale. If the issue still exists, please comment or update the issue, otherwise it will be closed after 7 days.

the issue still exists

**Comment by yanyiwu** [comment]
> > This issue has not been updated for over 1 year and will be marked as stale. If the issue still exists, please comment or update the issue, otherwise it will be closed after 7 days.
> 
> the issue still exists

Please try using nodejieba version 3.4.2. https://github.com/yanyiwu/nodejieba-demo
