### ISSUE TITLE
unable to install nodejieba@2.5.2 for arch=aarch

### ISSUE THREAD

**Issue by myalgo** [yanyiwu/nodejieba#216]
Hi,

While building nodejieba I get following error

| node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v83-linux-aarch64.tar.gz
| node-pre-gyp ERR! install request to https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v83-linux-aarch64.tar.gz failed, reason: read ECONNRESET
| node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@14.16.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
| node-pre-gyp WARN Hit error request to https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v83-linux-aarch64.tar.gz failed, reason: read ECONNRESET

node version 14.16
arch=aarch64

Please let me know how this can be resolved.

Thanks!

**Comment by myalgo** [comment]
Is there a way to override arch for nodejieba ?

**Comment by Mister-Hope** [comment]
https://github.com/yanyiwu/nodejieba/issues/223#issuecomment-1565204651
