### ISSUE TITLE
can not build in electron

### ISSUE THREAD

**Issue by dck1997** [yanyiwu/nodejieba#218]
nodejieba可以正常npm install，但运行打包过程中报错，报错日志显示请求https://cdn.npmmirror.com/binaries/nodejieba/v2.5.2/nodejieba-v2.5.2-electron-v9.1-win32-x64.tar.gz，观看源码后发现是因为node_abi返回的是electron-v9.1，并不是node-v83

**Comment by dck1997** [comment]
node-pre-gyp info using node-pre-gyp@1.0.10
    node-pre-gyp info using node@14.16.0 | win32 | x64
    node-pre-gyp http GET https://cdn.npmmirror.com/binaries/nodejieba/v2.5.2/nodejieba-v2.5.2-electron-v9.1-win32-x64.tar.gz
    node-pre-gyp ERR! install response status 404 Not Found on https://cdn.npmmirror.com/binaries/nodejieba/v2.5.2/nodejieba-v2.5.2-electron-v9.1-win32-x64.tar.gz
    node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and electron@9.1.2 (electron-v9.1 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp WARN Hit error response status 404 Not Found on https://cdn.npmmirror.com/binaries/nodejieba/v2.5.2/nodejieba-v2.5.2-electron-v9.1-win32-x64.tar.gz

**Comment by 1gao-176** [comment]
我的也是
