### ISSUE TITLE
Lacking of maintenance

### ISSUE THREAD

**Issue by Mister-Hope** [yanyiwu/nodejieba#223]
All support version of Node.js of this package has been moved out of Node LTS, I made a huge refactor for this repo to make this repo "becomes modern again".

It would be nice for @yanyiwu to gives a reply for this issue when you see this, describing how you see that PR. 

If you are busy in real life, I would happy to take over this project by inviting me as a collaborator. And if you do not have time to review that PR, I would appreciate if you can inform me, so that I will keep working in my forked repo and release it as a new package.

**Comment by Mister-Hope** [comment]
I released a package called `nodejs-jieba`

**Comment by hevi1991** [comment]
```
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path C:\Users\hazz\Workspaces\demos\node_modules\nodejs-jieba
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Users\hevi1\Workspaces\msme-times\node_modules\node-pre-gyp\bin\node-pre-gyp'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.14.2

npm ERR! A complete log of this run can be found in:
```
threw this ERR

**Comment by Mister-Hope** [comment]
> ```
> npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
> npm ERR! code 1
> npm ERR! path C:\Users\hazz\Workspaces\demos\node_modules\nodejs-jieba
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
> npm ERR! node:internal/modules/cjs/loader:1078
> npm ERR!   throw err;
> npm ERR!   ^
> npm ERR!
> npm ERR! Error: Cannot find module 'C:\Users\hevi1\Workspaces\msme-times\node_modules\node-pre-gyp\bin\node-pre-gyp'
> npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
> npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
> npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> npm ERR!     at node:internal/main/run_main_module:23:47 {
> npm ERR!   code: 'MODULE_NOT_FOUND',
> npm ERR!   requireStack: []
> npm ERR! }
> npm ERR!
> npm ERR! Node.js v18.14.2
> 
> npm ERR! A complete log of this run can be found in:
> ```
> threw this ERR

you mean my package or his package?

**Comment by hevi1991** [comment]
yours~I run `npm install nodejs-jieba`

**Comment by hevi1991** [comment]
> yours~I run `npm install nodejs-jieba`

I resolved, It needs install node-pre-gyp too.
```
npm install node-pre-gyp nodejs-jieba
```

**Comment by Mister-Hope** [comment]
I will test later with nom, at least yarn legacy and pnpm are working fine.

**Comment by yanyiwu** [comment]
i am so busy in real life, and i have invited you as a collabrator of this project already; 
and [nodejs-jieba](https://github.com/Mister-Hope/nodejs-jieba) is also good solution to continue the github life of nodejieba. you can do what you want. thank you
