### ISSUE TITLE
nodejieba.node is not a valid Win32 application

### ISSUE THREAD

**Issue by UtherPim** [yanyiwu/nodejieba#229]
开发环境：
node@16.8.0
nodejieba@2.6.0
electron@16.0.2
macOS Sonoma@14
正常运行。

使用electron-builder打包成window安装包后：
运行平台win7、x64
启动报错：nodejieba.node is not a valid Win32 application.

是nodejieba_binary有平台区分吗？

**Comment by wth1107** [comment]
解决了吗 兄弟

**Comment by UtherPim** [comment]
没有，用了另一个分词器 [node-analyzer](https://github.com/newebug/node-analyzer)

**Comment by wth1107** [comment]
> 没有，用了另一个分词器 [node-analyzer](https://github.com/newebug/node-analyzer)

我也放弃了 用了百度的粉分词接口(꒦_꒦)

**Comment by qq295823929** [comment]
我前一秒还好好的,突然重新run dev之后,就出现这个问题,也是醉了

**Comment by MrWeilian** [comment]
用这个 `@node-rs/jieba` 试试吧，我已经用了...

**Comment by yanyiwu** [comment]
用3.4.1 及以上版本试试。 https://github.com/yanyiwu/nodejieba-demo
