### ISSUE TITLE
请介绍下这个库的阻塞式和非阻塞式区别？

### ISSUE THREAD

**Issue by hotoo** [yanyiwu/nodejieba#23]
我觉得分词模块更多的应该还是是计算而不是 IO 上，因此『非阻塞式』真的是非阻塞的么？还是只是为了『遵循』Node 很多场景都使用非阻塞式的 API ？

如果是真的非阻塞，请多指教 ：）

**Comment by yanyiwu** [comment]
很遗憾的回复你：你说的都是对的。

1. 分词模块确实是CPU密集型的过程。
2. 这里的非阻塞只是为了遵循Node的非阻塞式api而已。

**Comment by hotoo** [comment]
既然这样，建议还是统一只提供同步 API 即可。
Node 的异步不是为了 API  异步而异步，而且 Node 很多内置模块也是不提供异步 API 的，
比如 [path](https://iojs.org/api/path.html), [querystring](https://iojs.org/api/querystring.html) 等等。

**Comment by yanyiwu** [comment]
确实，不过暂时还是把两种api都提供着吧，再后面的大版本再改吧。

**Comment by yanyiwu** [comment]
在最新的 v1.0.0 版本里面，只提供阻塞方法的功能函数。
