### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by andy27182** [yanyiwu/nodejieba#232]
when i use npm i in a project, i found an error log in terminal. However the project can work well without fixing this error. I'm not sure whether it is a bug.

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v83-win32-x64.tar.gz

**Comment by PrinOrange** [comment]
Your can replace it with `@node-rs/jieba` package that is the binding writed with rust.
It doesn't need the gyp.
https://www.npmjs.com/package/@node-rs/jieba
