### ISSUE TITLE
目前发现最新版本3.4.3不支持node20.18.0

### ISSUE THREAD

**Issue by BlowsBreeze** [yanyiwu/nodejieba#238]
18.20.4是支持的，因为我看官网v20.18.0也是(LTS)。
是否在readme中标注支持版本比较合适
(￣▽￣)

**Comment by yanyiwu** [comment]
https://github.com/yanyiwu/nodejieba-demo/actions/runs/11202288975/job/31138215386

**Comment by yanyiwu** [comment]
我看v20.18.0 测试也是通过的，你是在什么情况下发现不支持node20.18.0 呢，可以给一些信息帮助参考么

**Comment by BlowsBreeze** [comment]
我今天用最简单示例测试了确实可以，感谢回复。
