### ISSUE TITLE
能否暴露 add_word接口？

### ISSUE THREAD

**Issue by daiheitan** [yanyiwu/nodejieba#32]
原 `jieba` 分词中有个`add_word` 可以在运行中动态加词，希望能把这个API放出来。
另外现在的 `.load` 函数必须一次性添加五个dict，不太合理吧。

**Comment by yanyiwu** [comment]
1. `add_word` 动态加词这个API接口确实应该提供，预计这两条内搞定这个API。
2. `.load` 函数对于用户来说是屏蔽的，用户不需要调用啊。其次，一次性添加5个dict，这5个dict各司其职，
所以nodejieba才可以提供多种算法的分词和关键词抽取等功能。之后会对这些词典在README.md里面详细介绍。

**Comment by daiheitan** [comment]
那比如用户要自定义字典的时候，难道要自己添加词到user.dict.utf8 吗，这个文件随着npm package分发的，以node的编程习惯，不会改动安装的包里面的文件。所以这样不合适吧。

**Comment by yanyiwu** [comment]
@daiheitan 恩，我之所以隐藏load函数，是为了让用户更容易上手。不过你说的这个问题确实存在。
我先把`add_word`这个API加上。
关于load函数的问题，你有什么建议也可以说说。

**Comment by daiheitan** [comment]
其实不要强制加载五个就好了啊- -

**Comment by yanyiwu** [comment]
在新版本里面已经加上 `insertWord` 接口。
`npm install nodejieba@1.1.0` 
示例程序见 `test/demo.js`

**Comment by hotoo** [comment]
我觉得大部分普通用户不会关系词典本身，只要结果是期望的。

如果你关心到词典部分，你可能需要自己的 fork。

**Comment by daiheitan** [comment]
楼上你这想法很没意思。
一个工具型package应该努力提供适当的功能，而不是说，你想要这个那你去fork
何况词典本身就是一个分词工具的核心。

**Comment by hotoo** [comment]
我的意思是 Fork & PR

**Comment by daiheitan** [comment]
你乐意你来 XD
我懒，我就提提

**Comment by yanyiwu** [comment]
两位的需求都很合理，按我的理解，需求就是同时满足下面两点：

1. 用户无需主动调用load去载入词典也可以使用切词功能。
2. 用户需要使用自己的词典时，可以主动调用函数load去载入自己的词典，而不是去修改默认的词典。

现在已经想到一个能同时满足的办法，昨天睡觉前已经开发得差不多了，等我再修改修改就发布。

**Comment by yanyiwu** [comment]
搞定了，nodejieba@1.2.0 同时满足这两者，也顺带更新了 README.md 。有空可以试试。

**Comment by smilechun** [comment]
is it possible to insert user word with tag and weight?

**Comment by kilik52** [comment]
> is it possible to insert user word with tag and weight?

I know it's late, but after reading the source code, the tag is supported.

just call
````
nodejieba.insertWord('男默女泪', 'yourtag');
````

I did not found how to set the weight when calling insertWord though
