### ISSUE TITLE
多次调用 load 导致内存暴涨…

### ISSUE THREAD

**Issue by tiant167** [yanyiwu/nodejieba#33]
多次load userdict时，内存涨的很快。
我不太清楚 load 是增量增加字典还是会重新载入一遍userDict？

**Comment by yanyiwu** [comment]
是的，这个当时写的比较匆忙，没有考虑重复load的情况（当时也没想到会有人去重复load）。下个版本修复这个问题。

**Comment by yanyiwu** [comment]
`npm install nodejieba@1.2.1` 最新版已经修复了这个问题，你试试。

**Comment by tiant167** [comment]
感谢~！ 其实重复 load 是想删掉一个已经加入字典的单词，但我没有找到类似 removeWord 这样的功能~

**Comment by yanyiwu** [comment]
removeWord 也应该有。找时间加上。
