### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [yanyiwu/nodejieba#39]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [DictTrie](https://github.com/yanyiwu/nodejieba/blob/6a63d41e04a81c1afb9f7dd6cc2f4fef59abe95a/lib/CppJieba/DictTrie.hpp#L34 "Destructor for DictTrie")
* [load](https://github.com/yanyiwu/nodejieba/blob/a45456391eb63620638818ffa2f6433df62c410c/lib/nodejieba.cpp#L5 "load function")

**Comment by yanyiwu** [comment]
@elfring You are right! Thank you very much!

**Comment by yanyiwu** [comment]
Fixed it at `nodejieba@1.4.1`

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/yanyiwu/nodejieba/commit/a87b9ce18f6891ebd4d77f7d14e7ad0626f9c900 "Deletion of two unnecessary checks").
