### ISSUE TITLE
node 4.0 node-gyp 报错

### ISSUE THREAD

**Issue by lvsenlin** [yanyiwu/nodejieba#40]
.node-gyp/4.0.0/src/node.h:42:10: fatal error: 'v8.h' file not found
一直报gyp相关的错

**Comment by yanyiwu** [comment]
能贴更详细点的报错信息吗？光从现在这个错误信息来看的话，应该不是nodejieba的问题。

**Comment by lvsenlin** [comment]
我把NODE降级了，官方有关于gyp的讨论，应该是官方的问题
后面再升级吧

**Comment by yanyiwu** [comment]
好的，那这个issue我也关了吧。
