### ISSUE TITLE
请问现在cut支持异步调用吗?

### ISSUE THREAD

**Issue by gogoout** [yanyiwu/nodejieba#41]
因为在<http://yanyiwu.com/work/2015/03/21/nodejs-asynchronous-insight.html>中说cut支持传递一个callback,但是`demo.js`中没有相关的用法

而我自己代码中传递callback结果wordlist还是同步返回了,所以想问一下,多谢

**Comment by hotoo** [comment]
#23

**Comment by gogoout** [comment]
THX
