### ISSUE TITLE
centos6.5 Node.js4.2 编译报错

### ISSUE THREAD

**Issue by imseon** [yanyiwu/nodejieba#42]
[root@i-2atypla1 firstre]# npm install nodejieba
npm WARN package.json carrier@1.0.0 No repository field.
npm WARN package.json carrier@1.0.0 No license field.
|
> nodejieba@1.4.1 install /root/code/firstre/node_modules/nodejieba
> node-gyp rebuild

make: Entering directory `/root/code/firstre/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
In file included from /root/.node-gyp/4.2.0/include/node/node.h:42,
                 from ../lib/utils.h:4,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/root/.node-gyp/4.2.0/include/node/v8.h:336: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/4.2.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/4.2.0/include/node/v8.h:353: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/4.2.0/include/node/v8.h:360: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/4.2.0/include/node/v8.h:364: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/4.2.0/include/node/v8.h:430: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/4.2.0/include/node/v8.h:469: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/4.2.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/4.2.0/include/node/v8.h:790: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/4.2.0/include/node/v8.h:815: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/4.2.0/include/node/v8.h:827: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/4.2.0/include/node/v8.h:852: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/4.2.0/include/node/v8.h:1089: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h:1095: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/4.2.0/include/node/v8.h:3205: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/4.2.0/include/node/v8.h:7164: 错误：‘nullptr’在此作用域中尚未声明
In file included from ../node_modules/nan/nan.h:182,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../node_modules/nan/nan_maybe_43_inl.h:13: 错误：expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16: 错误：expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:24: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:31: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:36: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:41: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:46: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:51: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:60: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:65: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:70: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:77: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:84: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:92: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:99: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:109: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:115: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:119: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:126: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:131: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:136: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:140: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:146: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:151: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:157: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:163: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:169: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:175: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:181: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:187: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:195: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:202: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:206: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:210: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:214: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:218: 错误：expected initializer before ‘<’ token
In file included from ../node_modules/nan/nan.h:187,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan_converters.h:14: 错误：ISO C++ 不允许声明无类型的‘MaybeLocal’
../node_modules/nan/nan_converters.h:14: 错误：expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:16: 错误：ISO C++ 不允许声明无类型的‘Maybe’
../node_modules/nan/nan_converters.h:16: 错误：expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:26: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:27: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:28: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:29: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:30: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:31: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:32: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:42: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:43: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:44: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:45: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_converters.h:46: 错误：‘return_t’没有命名一个类型
In file included from ../node_modules/nan/nan_converters.h:59,
                 from ../node_modules/nan/nan.h:187,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan_converters_43_inl.h:18: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::Boolean>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:19: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::Number>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:20: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:21: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::Object>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:22: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::Integer>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:23: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::Uint32>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:24: 错误：‘return_t’在类‘Nan::imp::ToFactory<v8::Int32>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:34: 错误：‘return_t’在类‘Nan::imp::ToFactory<bool>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:35: 错误：‘return_t’在类‘Nan::imp::ToFactory<double>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:36: 错误：‘return_t’在类‘Nan::imp::ToFactory<long int>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:37: 错误：‘return_t’在类‘Nan::imp::ToFactory<unsigned int>’中没有命名一个类型
../node_modules/nan/nan_converters_43_inl.h:38: 错误：‘return_t’在类‘Nan::imp::ToFactory<int>’中没有命名一个类型
In file included from ../node_modules/nan/nan.h:188,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../node_modules/nan/nan_new.h:21: 错误：对‘To(v8::Local<v8::Integer>&)’的调用没有匹配的函数
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../node_modules/nan/nan_new.h:28: 错误：对‘To(v8::Local<v8::Integer>&)’的调用没有匹配的函数
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../node_modules/nan/nan_new.h:35: 错误：对‘To(v8::Local<v8::Integer>&)’的调用没有匹配的函数
../node_modules/nan/nan_new.h: At global scope:
../node_modules/nan/nan_new.h:43: 错误：ISO C++ 不允许声明无类型的‘MaybeLocal’
../node_modules/nan/nan_new.h:43: 错误：expected ‘;’ before ‘<’ token
../node_modules/nan/nan_new.h:75: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:141: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:147: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:148: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:160: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:161: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:162: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:163: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:165: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:166: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:182: 错误：‘return_t’没有命名一个类型
../node_modules/nan/nan_new.h:183: 错误：‘return_t’没有命名一个类型
In file included from ../node_modules/nan/nan_new.h:189,
                 from ../node_modules/nan/nan.h:188,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan_implementation_12_inl.h:56: 错误：‘return_t’在类‘Nan::imp::Factory<v8::Date>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static v8::Local<v8::Function> Nan::imp::Factory<v8::Function>::New(void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>)’:
../node_modules/nan/nan_implementation_12_inl.h:90: 错误：‘NewInstance’在此作用域中尚未声明
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static v8::Local<v8::FunctionTemplate> Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../node_modules/nan/nan_implementation_12_inl.h:118: 错误：‘NewInstance’在此作用域中尚未声明
../node_modules/nan/nan_implementation_12_inl.h: At global scope:
../node_modules/nan/nan_implementation_12_inl.h:197: 错误：‘return_t’在类‘Nan::imp::Factory<v8::RegExp>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:216: 错误：‘return_t’在类‘Nan::imp::Factory<v8::Script>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:222: 错误：‘return_t’在类‘Nan::imp::Factory<v8::Script>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:254: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:262: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:268: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:275: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:281: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:286: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:347: 错误：‘return_t’在类‘Nan::imp::Factory<v8::UnboundScript>’中没有命名一个类型
../node_modules/nan/nan_implementation_12_inl.h:354: 错误：‘return_t’在类‘Nan::imp::Factory<v8::UnboundScript>’中没有命名一个类型
In file included from ../node_modules/nan/nan.h:188,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan_new.h:291: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_new.h:297: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_new.h:303: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_new.h:309: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_new.h:315: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_new.h:321: 错误：‘return_t’在类‘Nan::imp::Factory<v8::String>’中没有命名一个类型
../node_modules/nan/nan_new.h:327: 错误：‘return_t’在类‘Nan::imp::Factory<v8::RegExp>’中没有命名一个类型
In file included from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../node_modules/nan/nan.h:639: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../node_modules/nan/nan.h:639: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../node_modules/nan/nan.h:640: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../node_modules/nan/nan.h:640: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../node_modules/nan/nan.h:641: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../node_modules/nan/nan.h:641: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../node_modules/nan/nan.h:642: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../node_modules/nan/nan.h:642: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../node_modules/nan/nan.h:643: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../node_modules/nan/nan.h:643: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:651: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:673: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:689: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:702: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:719: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:725: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:733: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:740: 错误：expected initializer before ‘<’ token
../node_modules/nan/nan.h:746: 错误：expected initializer before ‘<’ token
/root/.node-gyp/4.2.0/include/node/v8.h: In member function ‘void Nan::Callback::SetFunction(const v8::Local<v8::Function>&)’:
/root/.node-gyp/4.2.0/include/node/v8.h:3021: 错误：依赖参数的查找找到了‘class v8::Set’
../node_modules/nan/nan.h:1366: 错误：  在调用‘Set’时
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1488: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../node_modules/nan/nan.h:1506: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:1540: 错误：对‘New(const char*)’的调用没有匹配的函数
../node_modules/nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1829: 错误：‘GetFunction’的实参不依赖模板参数，所以‘GetFunction’的声明必须可用
../node_modules/nan/nan.h:1829: 附注：(如果您使用‘-fpermissive’，G++ 会接受您的代码，但是允许使用未定义的名称是不建议使用的风格)
../node_modules/nan/nan.h:1830: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1842: 错误：‘GetFunction’在此作用域中尚未声明
../node_modules/nan/nan.h:1843: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<void>&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../node_modules/nan/nan.h:1868: 错误：‘NewInstance’在此作用域中尚未声明
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<void>&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1911: 错误：‘NewInstance’在此作用域中尚未声明
../node_modules/nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Local<v8::ObjectTemplate>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:1959: 错误：‘NewInstance’在此作用域中尚未声明
../node_modules/nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Local<v8::ObjectTemplate>, void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:2029: 错误：‘NewInstance’在此作用域中尚未声明
In file included from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../node_modules/nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:2090: 错误：对‘New(const char*&)’的调用没有匹配的函数
../node_modules/nan/nan.h:2091: 错误：‘GetFunction’在此作用域中尚未声明
/root/.node-gyp/4.2.0/include/node/v8.h:3021: 错误：依赖参数的查找找到了‘class v8::Set’
../node_modules/nan/nan.h:2091: 错误：  在调用‘Set’时
../node_modules/nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:2098: 错误：对‘To(v8::Local<v8::Value>&)’的调用没有匹配的函数
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../node_modules/nan/nan.h:2111: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../node_modules/nan/nan.h:2117: 错误：‘class v8::Local<v8::Boolean>’没有名为‘ToLocalChecked’的成员
In file included from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../lib/utils.h: In function ‘void WrapVector(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, v8::Local<v8::Array>&)’:
../lib/utils.h:19: 错误：对‘New(const char*)’的调用没有匹配的函数
../lib/utils.h: In function ‘void WrapPairVector(std::vector<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double>, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double> > >&, v8::Local<v8::Array>&)’:
../lib/utils.h:30: 错误：对‘New(const char*)’的调用没有匹配的函数
../lib/utils.h: In function ‘void WrapPairVector(std::vector<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, v8::Local<v8::Array>&)’:
../lib/utils.h:41: 错误：对‘New(const char*)’的调用没有匹配的函数
../lib/index.cpp: At global scope:
../lib/index.cpp:3: 错误：变量或字段‘init’声明为 void
../lib/index.cpp:3: 错误：‘Handle’在此作用域中尚未声明
../lib/index.cpp:3: 错误：expected primary-expression before ‘>’ token
../lib/index.cpp:3: 错误：‘exports’在此作用域中尚未声明
../lib/index.cpp:16: 错误：‘init’在此作用域中尚未声明
../lib/index.cpp:16: 错误：‘node::node_module’的初始值设定项太多
make: *** [Release/obj.target/nodejieba/lib/index.o] 错误 1
make: Leaving directory `/root/code/firstre/node_modules/nodejieba/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.30.3.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/code/firstre/node_modules/nodejieba
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nodejieba"
npm ERR! node v4.2.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@1.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@1.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/code/firstre/npm-debug.log

**Comment by yanyiwu** [comment]
1. 为了你这个issue，我特地把我的ubuntu从12.04升级到14.04（为了使用g++4.8，node.js 4.0之后的版本依赖c++11），然后安装了node 4.2.1 ，但是一切顺利啊。
2. 请问一下你的机器环境是？ g++版本是？

**Comment by imseon** [comment]
我现在的版本是：4.4.7
我升级下试试看，还真是不知道依赖的编译器变了，多谢！

**Comment by yanyiwu** [comment]
你是用的centos？那你的nodejs4.2 是怎么安装的？不可能是用源码编译安装的吧？因为源码编译就需要c++11.

**Comment by imseon** [comment]
嗯，不是编译安装，是通过 https://github.com/tj/n 这个工具安装的
我在尝试升级gcc和g++

**Comment by imseon** [comment]
多谢@yanyiwu，升级了gcc之后，编译没问题了！
