### ISSUE TITLE
freebsd 安装失败 gyp ERR! build error 

### ISSUE THREAD

**Issue by nroe** [yanyiwu/nodejieba#43]
freebsd 10.1
nodejs v0.11.16
npm 2.14.4
部分日志是这样的：

> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@0.11.16 | freebsd | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/www/xiongzhanghao.com/node_modules/nodejieba/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.11.16/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.11.16',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/www/xiongzhanghao.com/node_modules/nodejieba',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn gmake
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gmake: Entering directory '/www/xiongzhanghao.com/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
In file included from ../lib/index.cpp:1:
In file included from ../lib/nodejieba.h:5:
In file included from ../lib/CppJieba/Application.hpp:4:
In file included from ../lib/CppJieba/QuerySegment.hpp:8:
In file included from ../lib/CppJieba/DictTrie.hpp:11:
In file included from ../lib/CppJieba/limonp/StringUtil.hpp:24:
../lib/CppJieba/limonp/StdExtension.hpp:19:12: error: no member named 'tr1' in namespace 'std'
using std::tr1::unordered_map;
      ~~~~~^
../lib/CppJieba/limonp/StdExtension.hpp:20:12: error: no member named 'tr1' in namespace 'std'
using std::tr1::unordered_set;
      ~~~~~^
2 errors generated.
nodejieba.target.mk:91: recipe for target 'Release/obj.target/nodejieba/lib/index.o' failed
gmake: *** [Release/obj.target/nodejieba/lib/index.o] Error 1
gmake: Leaving directory '/www/xiongzhanghao.com/node_modules/nodejieba/build'

gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System FreeBSD 10.1-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /www/xiongzhanghao.com/node_modules/nodejieba
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm info nodejieba@1.4.1 Failed to exec install script
npm ERR! FreeBSD 10.1-RELEASE
npm ERR! argv "node" "/usr/local/bin/npm" "install" "nodejieba" "-d"
npm ERR! node v0.11.16
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

**Comment by yanyiwu** [comment]
请问一下你的g++版本是？

**Comment by nroe** [comment]
# gcc48 --version
gcc48 (FreeBSD Ports Collection) 4.8.5
# gmake -v
GNU Make 4.1
Built for amd64-portbld-freebsd10.1
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by yanyiwu** [comment]
目测是编译器的问题，
@nroe 能贴一下 `g++ -v` 这个命令输出的内容吗？

**Comment by nroe** [comment]
我后来又装了一个 5，2个都贴给你：），谢谢看下

root@iZ11gxi3y1lZ:/www/xiongzhanghao.com # g++48 -v
Using built-in specs.
COLLECT_GCC=g++48
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.5/lto-wrapper
Target: x86_64-portbld-freebsd10.1
Configured with: ./../gcc-4.8.5/configure --disable-bootstrap --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc48 --libexecdir=/usr/local/libexec/gcc48 --program-suffix=48 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc48/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --with-ecj-jar=/usr/local/share/java/ecj-4.5.jar --enable-languages=c,c++,objc,fortran,java --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc48 --build=x86_64-portbld-freebsd10.1
Thread model: posix
gcc version 4.8.5 (FreeBSD Ports Collection) 
root@iZ11gxi3y1lZ:/www/xiongzhanghao.com # g++5 -v
Using built-in specs.
COLLECT_GCC=g++5
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc5/gcc/x86_64-portbld-freebsd10.1/5.2.0/lto-wrapper
Target: x86_64-portbld-freebsd10.1
Configured with: ./../gcc-5.2.0/configure --with-build-config=bootstrap-debug --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc5 --libexecdir=/usr/local/libexec/gcc5 --program-suffix=5 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc5/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --with-ecj-jar=/usr/local/share/java/ecj-4.5.jar --enable-languages=c,c++,objc,fortran,java --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc5 --build=x86_64-portbld-freebsd10.1
Thread model: posix
gcc version 5.2.0 (FreeBSD Ports Collection)

**Comment by yanyiwu** [comment]
你的系统里面没有g++这个可执行文件（或者软连接）吗？
如果有的话请贴一下好吗？
这样才能先确定g++到底使用的是哪个版本的g++。
你光告诉我g++5的版本没用啊。

**Comment by nroe** [comment]
@yanyiwu  应该是g++48 没有g++，也没有软链接。你先看下 48 的是否漏了什么类库还是什么。

**Comment by yanyiwu** [comment]
如果从版本来说g++4.8以上的肯定没问题了。怀疑有可能是你的g++以前是很旧的版本吧？然后include的头文件是古老的文件？

可以的话请提供一下 
```
ls -al /usr/incude/c++*
```
的结果。

**Comment by nroe** [comment]
@yanyiwu 有Q 或其他实时的 IM 吗，找到 /usr/local/include/ 也没有 C++ 相关的文件 ：（

**Comment by nroe** [comment]
你打错了，我看了下，请看结果。。。。

# ls -al /usr/include/c++*
total 20
drwxr-xr-x   4 root  wheel   512 Nov 12  2014 .
drwxr-xr-x  53 root  wheel  6144 Nov 12  2014 ..
drwxr-xr-x   7 root  wheel   512 Nov 12  2014 4.2
drwxr-xr-x   5 root  wheel  2048 Nov 12  2014 v1

**Comment by yanyiwu** [comment]
@nroe 加我一下qq 64162451

**Comment by nroe** [comment]
在 @yanyiwu  的帮助下解决了。
1. clone git 代码
2. 修改代码 vim lib/CppJieba/limonp/StdExtension.hpp 将
using std::tr1::unordered_map;
using std::tr1::unordered_set;
改为：
using std::unordered_map;
using std:::unordered_set;
3. node-gpy build 源代码
4. 复制目录到 node_modules 即可使用

**Comment by yanyiwu** [comment]
主要是兼容性问题，但是目前没有找到很好的在所有环境下兼容tr1的方法。
