### ISSUE TITLE
Node 4.2.2编译失败【.node-gyp/4.2.2/common.gypi not found】

### ISSUE THREAD

**Issue by SinalVee** [yanyiwu/nodejieba#44]
看了下.node-gyp/4.2.2目录，common.gypi文件在4.2.2/include/node文件夹中

**Comment by yanyiwu** [comment]
@SinalVee  请问一下，你是编译 node失败，还是编译 nodejieba 失败。

**Comment by SinalVee** [comment]
@yanyiwu 我用gitbook安装search-pro的时候编译nodejieba失败，错误提示就是【.node-gyp/4.2.2/common.gypi not found】，npm直接安装nodejieba正常，好奇怪。

**Comment by yanyiwu** [comment]
@SinalVee 
1. 哦我才知道有gitbook的插件使用了nodejieba支持中文搜索，很酷！
2. 目测可能是你安装 search-pro 时候的问题吧，应该不是 nodejieba 的问题，不过具体定位问题可能得需要我也使用一下 gitbook 试试，才能定位。我以前没有使用过 gitbook 的插件。

**Comment by yanyiwu** [comment]
@SinalVee 很忧伤，gitbook init 一直在installing。。。你那边能不能把完整的报错信息贴一下呢？

**Comment by SinalVee** [comment]
@yanyiwu 我也很忧伤 :( ，gitbook install打不出全部的log，只有一点点错误信息
> info: install plugin search-pro from npm (gitbook-plugin-search-pro) with version 1.0.5 
> (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
> gyp: /home/sinalvee/.node-gyp/4.2.2/common.gypi not found (cwd: /home/sinalvee/github/hbu-wiki/node_modules/gitbook-plugin-search-pro/node_modules/nodejieba) while reading includes of binding.gyp while trying to load binding.gyp
> 
> Error: nodejieba@1.4.1 install: `node-gyp rebuild`
> Exit status 1

gitbook使用npmi包来安装插件，loglevel是silent，我把loglevel改成info之后还是这些错误信息，而且npm-debug.log文件也没有生成。。

**Comment by SinalVee** [comment]
搞清楚了！！！
gitbook使用的npm版本是2.4.1，npm@2.14.4修复了这个issue！
怪不得gitbook install报错，直接npm install正常。
请允许我做一个日狗的表情。。。

**Comment by yanyiwu** [comment]
@SinalVee 赞！修复了就好。

**Comment by xunuo** [comment]
@SinalVee 赞！修复了就好。
