### ISSUE TITLE
centos6.5  node 0.12.10 编译不成功

### ISSUE THREAD

**Issue by IssicLzx** [yanyiwu/nodejieba#50]
错误如下：

[root@localhost jieba]# cnpm install nodejieba
-
> nodejieba@1.4.9 install /dtedu/node_modules/nodejieba
> node-gyp rebuild

make: Entering directory `/dtedu/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
make: g++ï¼šå‘½ä»¤æœªæ‰¾åˆ°
make: *** [Release/obj.target/nodejieba/lib/index.o] é”™è¯¯ 127
make: Leaving directory `/dtedu/node_modules/nodejieba/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/dtedu/node-v0.12.10-linux-x64/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/dtedu/node-v0.12.10-linux-x64/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /dtedu/node_modules/nodejieba
gyp ERR! node -v v0.12.10
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "node" "/dtedu/node-v0.12.10-linux-x64/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/root/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/dtedu/node-v0.12.10-linux-x64/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "nodejieba"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.21
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@1.4.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@1.4.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodejieba
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /dtedu/jieba/npm-debug.log

请求作者帮忙解决下

**Comment by yanyiwu** [comment]
@IssicLzx 我刚在centos6.5 上面安装了 node 0.12.10 版本，然后

```
cnpm i nodejieba
-
> nodejieba@1.4.9 install /tmp/node_modules/nodejieba
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
  CXX(target) Release/obj.target/nodejieba/lib/nodejieba.o
  SOLINK_MODULE(target) Release/obj.target/nodejieba.node
  COPY Release/nodejieba.node
make: Leaving directory `/tmp/node_modules/nodejieba/build'
nodejieba@1.4.9 node_modules/nodejieba
```

一切正常啊，你确定是nodejieba的问题吗？

**Comment by IssicLzx** [comment]
额，这样我不太知道是什么问题，会是node-gyp的问题吗？ gyp ERR! stack Error: make failed with exit code: 2

**Comment by yanyiwu** [comment]
你是在哪个目录下运行 `cnpm install nodejieba`  的？
你试试运行一下 `cnpm install nan` 看结果是啥？

**Comment by IssicLzx** [comment]
安装成功 没问题
[root@localhost jieba]# cnpm install nan
nan@2.2.0 ../node_modules/nan

**Comment by yanyiwu** [comment]
是不是你所在目录的目录名字冲突之类的？你能不能 `cd /tmp && cnpm install nodejieba` 试试？

**Comment by IssicLzx** [comment]
你c++ 是用什么的

**Comment by IssicLzx** [comment]
我是gcc 4.4.7

**Comment by yanyiwu** [comment]
一样：
```
gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)
```

**Comment by IssicLzx** [comment]
cd /tmp && cnpm install nodejieba 试了 还是报相同的错误

**Comment by IssicLzx** [comment]
可以说下你得 node-gyp 是什么版本吗？

**Comment by yanyiwu** [comment]
我是通过node安装的node 0.12.10(./configure&&make&&sudo make install)

这样安装的时候会自带 安装npm

```
npm -v
2.14.9
```

同时安装npm的时候也会安装node-gyp ：

```
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp -v
v3.0.3
```

**Comment by IssicLzx** [comment]
我的node-gyp 应该是node-gyp的问题
[root@localhost tmp]# node-gyp -v
v3.3.0

**Comment by yanyiwu** [comment]
是不是你的node-gyp和node的版本不匹配。之前好像遇到过因为两者版本不匹配导致的问题。

**Comment by IssicLzx** [comment]
我的node 0.12.10 是从官网wget 下来 然后解压使用的 好像下下来 node-gyp是3.3

**Comment by yanyiwu** [comment]
然后呢，你现在打算怎么办？重装一遍？这个issue和你的问题很像，可以参考一下：
https://github.com/hotoo/pinyin/issues/44

**Comment by IssicLzx** [comment]
我看node那边说是node-gyp 3.3 要用 gcc 4.8才可以 我先下载gcc 4.8 试试 不行就把node 重新编译安装

**Comment by IssicLzx** [comment]
更新完gcc 后测试成功

**Comment by yanyiwu** [comment]
那看来确实是因为node-gyp版本太高级了。我记得 node-0.12.10 是不需要 gcc4.8的。

**Comment by onvno** [comment]
Mark下，遇到问题了，回去看看是不是一样的
