### ISSUE TITLE
不能够自己配关键词

### ISSUE THREAD

**Issue by JasonTy** [yanyiwu/nodejieba#51]

**Comment by yanyiwu** [comment]
你是说自己配词典吧？可以啊。有个load函数可以主动调用，示例请看 https://github.com/yanyiwu/nodejieba/blob/master/test/load_dict_demo.js

**Comment by JasonTy** [comment]
不是，我说的是cut函数不能够返回分词的权重，因为，现在我只能够配自己的分词库，但是权重这块，却取不到

**Comment by JasonTy** [comment]
当我调用cut函数时，他的返回值是：
[ '华宸信托', '－', '青岛裕龙', ' ', '国泰君安', '期货', '－', '智信3号' ]
但是我期望的返回值是：
[ '华宸信托：10', '－:9', '青岛裕龙:8', ' ', '国泰君安:7', '期货:6', '－:9', '智信3号:5' ]
这样我就可以在结果拿到权重了，可以用这个权重来干其他的，比如排序

**Comment by yanyiwu** [comment]
哦我明白你的意思了。不过权重的话只有在extract函数里面有意义。在cut里面没什么意义。那是要增加一个extract函数返回带权重的词语信息吗？

**Comment by JasonTy** [comment]
是的，增加一个带权重的extract函数可以解决这个问题。
想再问一下：
extract函数是从字典中提取关键字吗，包括用户字典吗？

顺便请问下，idf里面的数值和权重有什么区别？

**Comment by yanyiwu** [comment]
权重是tf-idf算法，你可以搜一下tf-idf算法了解一下。
