### ISSUE TITLE
使用 extract 时，可以不返回词频么

### ISSUE THREAD

**Issue by blade254353074** [yanyiwu/nodejieba#57]

**Comment by yanyiwu** [comment]
首先，那个不是词频，是tfidf的分值。然后，如果我不返回分值的话，又会有另一个issue问我为什么不返回分值。
所以我还是选了返回分值。

**Comment by blade254353074** [comment]
好吧。。。那可不可以修改返回的数据结构

如果需要`tfidf`分值，则返回
```javascript
[{ value: "str", tfidf: 0.1 }]
```

不需要的话，返回
```javascript
["str"]
```

我也只是建议下，用`map`、`slice`多操作那么下有些不简洁

**Comment by yanyiwu** [comment]
众口难调啊，这个暂时就不改了哈。

**Comment by blade254353074** [comment]
@yanyiwu 没事~
