### ISSUE TITLE
win764 node 0.12.1 vs2013环境  nodejieba编译通过  gitbook中文搜索正常使用

### ISSUE THREAD

**Issue by ruofei001** [yanyiwu/nodejieba#59]
gitbook install 会报nodejieba出错，进入nodejieba目录 node-gyp rebuild ,然后gitbook build

**Comment by yanyiwu** [comment]
错误信息能贴一下吗

**Comment by ruofei001** [comment]
D:\WebstormProjects\help\h2\zh>gitbook install
info: 5 plugins to install
info: No version specified, resolve plugin search-pro
info: install plugin search-pro from npm (gitbook-plugin-search-pro) with version 1.0.9
-
D:\WebstormProjects\help\h2\zh\node_modules\gitbook-plugin-search-pro\node_modules\nodejieba>node "C:\Users\Administrator\.gitbook\versions\2.6.7\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(214,5): error MSB4175: 未能从程序集“C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Build.Tasks.v12.0.dll”加载任务工厂“CodeTaskFactory”。用于启动进程的环境块不能多于 65535 个字节。  您的环境块的长度为 201064 个字节。  请移除一些环境变量，然后再试一次。 [D:\WebstormProjects\help\h2\zh\node_modules\gitbook-plugin-search-pro\node_modules\nodejieba\build\nodejieba.vcxproj]

**Comment by ruofei001** [comment]
Error: nodejieba@1.4.11 install: `node-gyp rebuild`
Exit status 1

**Comment by yanyiwu** [comment]
@ruofei001 能参考一下 http://www.jianshu.com/p/d541c8585479  这个吗
