### ISSUE TITLE
v2.2.1 tag function does not work?

### ISSUE THREAD

**Issue by npes87184** [yanyiwu/nodejieba#60]
[ { word: '红掌', tag: 'x' },
  { word: '拨', tag: 'x' },
  { word: '清波', tag: 'x' } ]

In my test, it always returns x.

**Comment by npes87184** [comment]
I find it is because of your user.dict spec is different from python jieba.

In python jieba, the user dictionary has three elements.

I think the problem can be solved by changing `nodejieba/deps/cppjieba/DictTrie.hpp`

Line 114: `(buf.size() == 2 ? buf[1] : UNKNOWN_TAG));` to `(buf.size() == 3 ? buf[2] : UNKNOWN_TAG));`

**Comment by yanyiwu** [comment]
ok,thank you,and i will fix it tonight

**Comment by npes87184** [comment]
I submit a PR. I have tested it. I think it is work now. btw, why you use default weight for user dictionary in Line 113?

**Comment by yanyiwu** [comment]
@npes87184 are you the same person as @bigelephant29 ?
why don't you just reuse the https://github.com/yanyiwu/cppjieba/pull/73  to make this pull request?

**Comment by npes87184** [comment]
No, man. We are in the same company and use you work to build something wonderful!

I think the python jieba is the most popular tool for Chinese text segmentation. The spec of user defined dictionary should not be different from it. So, I modified the user dictionary and code to match the spec of python jieba. If you do not like it. I can reuse the latest PR in cppjieba into this PR, tomorrow. Thanks.

**Comment by yanyiwu** [comment]
@npes87184 OK, wait for your pull request tomorrow. Thanks
