### ISSUE TITLE
2.x版本貌似变差了

### ISSUE THREAD

**Issue by flu1987** [yanyiwu/nodejieba#66]
1.*版本一句话分词结果:
 '汇通网',
  '月',
  '日讯',
  '高盛',
  '研究',
  '团队',
  '周五',

同一句话在2.x版本里面变成了:
'汇通网',
  '月',
  '日',
  '讯',
  '高'
  '盛',
  '研究',
  '团队',
  '周五'

加载的用户字典里面可是有 “高盛” 这个词汇的

**Comment by yanyiwu** [comment]
能提供一下具体的 2.x 是哪个版本吗？
