### ISSUE TITLE
win10 64位编译不通过

### ISSUE THREAD

**Issue by keyiis** [yanyiwu/nodejieba#72]
我的环境是win10 x64/nodejs 6.9.1/vc++2015/python 2.7.12,后来尝试换了 [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools),还是不通过，下面是错误消息，谢谢！

```
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  index.cpp
  nodejieba.cpp
  win_delay_load_hook.cc
c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h(800): fatal error C107
0: 文件“c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h”中的 #if/#endif 对不
匹配 (编译源文件 ..\lib\index.cpp) [D:\work\nodejs\angular\angular2-electron\node_modu
les\nodejieba\build\nodejieba.vcxproj]
c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h(800): fatal error C107
0: 文件“c:\users\administrator\.node-gyp\6.9.1\include\node\v8.h”中的 #if/#endif 对不
匹配 (编译源文件 ..\lib\nodejieba.cpp) [D:\work\nodejs\angular\angular2-electron\node_
modules\nodejieba\build\nodejieba.vcxproj]
```

**Comment by huguoba** [comment]
win764位+vs2012，目前我使用的nodejs只有0.12.x版本可以通过，试试吧，降低nodejs版本。

**Comment by keyiis** [comment]
@huguoba nodejs 降级到4.6终于通过了,但其它模块有需要至少node5.x,真是头大啊！

**Comment by autukill** [comment]
在使用 mern.io,它依赖这个库
win10 64bit 家庭版的没问题 ,另一个win10 64bit 企业版就报这错了.

**Comment by keyiis** [comment]
@autukill 因为项目要跟硬件交互，最近一直跟各种c++ addon在搞，也得出一点小经验， windows编译模块产生错误大致有以下几个原因
1、c++编译器环境也就是vs的版本
2、python 这个错误的可能性不大
3、node-gyp 是否安装了多个版本，比如一个全局，一个装项目下
4、nodejs版本 和 被编译模块需要的版本是否匹配
5、有些模块编译需要上墙外的网站下载头文件
6、如果我会写C++就好了

**Comment by yanyiwu** [comment]
谢谢！@keyiis
如果能把这些写在README.md里面提交pull request 就更好了。

**Comment by keyiis** [comment]
@yanyiwu 已提交，待项目结束再好好整理下过程中遇到的问题。非常感谢您贡献的“结巴”！

**Comment by yanyiwu** [comment]
@keyiis 有提交吗？我好象没有看到啊

**Comment by autukill** [comment]
@keyiis  
My bad
更新了Visual Studio2015，也就是安装了vc++  和 win8.1 sdk，之后编译通过了
