### ISSUE TITLE
不支持中英混合(py版支持)

### ISSUE THREAD

**Issue by luchenue** [yanyiwu/nodejieba#73]
python版：访问 www . baidu . com 进行 搜索
node版:      访问 w w w . b a i d u . c o m 进行 搜索

**Comment by yanyiwu** [comment]
@luchenue  https://github.com/yanyiwu/nodejieba/blob/master/test/test.js#L303

**Comment by luchenue** [comment]
@yanyiwu 
还是不行啊，能不能忙吗看下

> D:\Project\spa\f2>npm i nodejieba
(node:15136) fs: re-evaluating native module sources is not supported. If you ar
e using the graceful-fs module, please update it to a more recent version.

> nodejieba@2.2.4 install D:\Project\spa\f2\node_modules\nodejieba
> node-gyp rebuild


D:\Project\spa\f2\node_modules\nodejieba>if not defined npm_config_node_gyp (nod
e "C:\Users\L\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_
modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  index.cpp
  nodejieba.cpp
d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(19): warning C4267: “参数
”:
从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\lib\index.cpp) [D:\P
roject\spa\f2\node_
modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(19): warning C4267: “参数
”:
从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\lib\nodejieba.cpp) [
D:\Project\spa\f2\n
ode_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(35): warning C4267: “参数
”:
从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\lib\nodejieba.cpp) [
D:\Project\spa\f2\n
ode_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(35): warning C4267: “参数
”:
从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\lib\index.cpp) [D:\P
roject\spa\f2\node_
modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(51): warning C4267: “参数
”:
从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\lib\nodejieba.cpp) [
D:\Project\spa\f2\n
ode_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(51): warning C4267: “参数
”:
从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\lib\index.cpp) [D:\P
roject\spa\f2\node_
modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nan\nan_new.h(208): warning C4267: “参数”: 从“
size_
t”转换到“int”，可能丢失数据 (编译源文件 ..\lib\index.cpp) [D:\Project\spa\f2\
node_modules\node
jieba\build\nodejieba.vcxproj]
  d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(17): note: 参见对正在编译
的函数 模板
   实例化“v8::Local<v8::Array> Nan::New<v8::Array,unsigned __int64>(A0)”的引用

          with
          [
              A0=unsigned __int64
          ] (编译源文件 ..\lib\index.cpp)
d:\project\spa\f2\node_modules\nodejieba\deps\cppjieba\Unicode.hpp(141): warnin
g C4267: “参数”: 从“size_t”转换到“uint32_t”，可能丢失数据 (编译源文件 ..\l
ib\nodejieba.cpp) [D:\P
roject\spa\f2\node_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\deps\cppjieba\FullSegment.hpp(76): war
ning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据 (编译源文件 ..\lib\no
dejieba.cpp) [D:\Proj
ect\spa\f2\node_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\deps\cppjieba\HMMSegment.hpp(162): war
ning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据 (编译源文件 ..\lib\no
dejieba.cpp) [D:\Proj
ect\spa\f2\node_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nodejieba\deps\cppjieba\HMMSegment.hpp(178): war
ning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 (编译源文件 ..\l
ib\nodejieba.cpp) [D:\Pr
oject\spa\f2\node_modules\nodejieba\build\nodejieba.vcxproj]
d:\project\spa\f2\node_modules\nan\nan_new.h(208): warning C4267: “参数”: 从“
size_
t”转换到“int”，可能丢失数据 (编译源文件 ..\lib\nodejieba.cpp) [D:\Project\spa
\f2\node_modules\
nodejieba\build\nodejieba.vcxproj]
  d:\project\spa\f2\node_modules\nodejieba\lib\utils.h(17): note: 参见对正在编译
的函数 模板
   实例化“v8::Local<v8::Array> Nan::New<v8::Array,unsigned __int64>(A0)”的引用

          with
          [
              A0=unsigned __int64
          ] (编译源文件 ..\lib\nodejieba.cpp)
  win_delay_load_hook.c
    正在创建库 D:\Project\spa\f2\node_modules\nodejieba\build\Release\nodejieba.
lib
  和对象 D:\Project\spa\f2\node_modules\nodejieba\build\Release\nodejieba.exp
  正在生成代码
  已完成代码的生成
  nodejieba.vcxproj -> D:\Project\spa\f2\node_modules\nodejieba\build\Release\\
  nodejieba.node
D:\Project\spa\f2
`-- nodejieba@2.2.4
  `-- nan@2.3.5

npm WARN enoent ENOENT: no such file or directory, open 'D:\Project\spa\f2\packa
ge.json'
npm WARN f2 No description
npm WARN f2 No repository field.
npm WARN f2 No README data
npm WARN f2 No license field.

D:\Project\spa\f2>node
> require('nodejieba').cut('访问www.baidu.com')
[ '访问', 'w', 'w', 'w', '.', 'b', 'a', 'i', 'd', 'u', '.', 'c', 'o', 'm' ]
>


os WIN7 x64 
node 6.8.1

**Comment by luchenue** [comment]
@yanyiwu 
nodejieba.cut("访问www.baidu.com进行搜索", true)
请问第二参数true是什么意思？node版和ccp版都找不到参数说明

**Comment by yanyiwu** [comment]
就是开启hmm模式，默认的mp模式只会切割出词典里面有和词。

**Comment by luchenue** [comment]
@yanyiwu nodejiaba.cut( , true)和nodejiaba.cutHMM有用法区别吗？

**Comment by yanyiwu** [comment]
有，而且相差很大。

**Comment by luchenue** [comment]
@yanyiwu 
.cut( ,true) 先词典 剩下的hmm
.cutHMM 完全hmm
我理解的对吗？

**Comment by yanyiwu** [comment]
对

**Comment by luchenue** [comment]
谢谢
