### ISSUE TITLE
node 1.7.1 环境出现安装错误

### ISSUE THREAD

**Issue by simonguo** [yanyiwu/nodejieba#75]
Error: shasum check failed for /tmp/npm-24556-41ebcea7/registry.npmjs.org/nodejieba/-/nodejieba-2.2.4.tgz
Expected: b2874abf731c885bb3ca2dabf0a76a1eff4cdc1f
Actual:   a95b9b2bf4ec9c622b37b9a51663e742359c8d95
From:     https://registry.npmjs.org/nodejieba/-/nodejieba-2.2.4.tgz

**Comment by mygoodboy** [comment]
var nodejieba = require("./build/Release/nodejieba.node");
the file is not exist ，if it is a error or not

**Comment by simonguo** [comment]
Error: nodejieba@2.2.4 install: `node-gyp rebuild`
Exit status 1
