### ISSUE TITLE
win7安裝錯誤及過程 (內有win10問題安裝)

### ISSUE THREAD

**Issue by mygoodboy** [yanyiwu/nodejieba#76]
環境
win7 
node-v6.9.1-x64

以下是執行 npm install nodejieba 出現的錯誤

問題1 :: 無python等基礎軟件
執行  ##  npm install --global windows-build-tools

問題2
user\Desktop\getdata\node_modules\nodejieba\build\binding.sln :
無法載入 Visual C++ 元件 "VCBuild.exe"。如果未安裝此元件，請 1)
indows SD

安裝  ##  net4.51
https://www.microsoft.com/en-us/download/details.aspx?id=40779

問題3
C:\users\user\Desktop\getdata\node_modules\nodejieba\build\nodejieba.vcxproj(20
,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was n
ot found. Confirm that the path in the <Import> declaration is correct, and tha
t the file exists on disk.

MSB4019 找不到Microsoft.Cpp

確認是否有 Microsoft.Cpp 資料夾
C:\Program Files (x86)\MSBuild\Microsoft.Cpp  #(\v4.0\v140 )

安裝  ## build tools 2015(安裝後)
https://www.microsoft.com/zh-tw/download/details.aspx?id=48159

再次執行  ##  npm install --global windows-build-tools

就會可正常使用了
執行  npm install nodejieba  
就可以用node 執行demo.js做測試了

**Comment by yanyiwu** [comment]
你不要着急，换台干净的windows系统，装上 visual studio 2015，装上 npm node-gyp node ，然后再npm  install nodejieba 试试。

**Comment by mygoodboy** [comment]
非常感謝!!，我再試試看的
