### ISSUE TITLE
不支持 node v6.9.1吗？

### ISSUE THREAD

**Issue by chelsh** [yanyiwu/nodejieba#78]
![image](https://cloud.githubusercontent.com/assets/10752360/20829970/738d78e0-b8b9-11e6-9d06-52ca27ecc0d9.png)

**Comment by hotoo** [comment]
- https://github.com/hotoo/pinyin/issues/114
- https://github.com/hotoo/pinyin/issues/115

**Comment by clonn** [comment]
經過自己的測試，在測試的 project 裡面， package.json 的 name: 名稱值，不可以和其中的 dependency module 名稱一樣，否則會造成 npm install refuse.

建議修改， package.json 內容如下，

{
  "name": "nodejiebatest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "nodejieba": "^2.2.4"
  }
}
重新再把 node_modules 砍掉，再重新執行一次 npm install 就可以順利安裝了。
這是我發現的解法，提供參考 @chelsh
