### ISSUE TITLE
stop words not working?

### ISSUE THREAD

**Issue by b051** [yanyiwu/nodejieba#88]
this is from my console:
```bash
> var jieba = require('nodejieba')
undefined
> jieba.cut('一个十一岁 一个十三岁 一个十四岁')
[ '一个', '十一岁', ' ', '一个十三岁', ' ', '一个十四岁' ]
```
'个' is in the stop words file, does '一个十三岁' have more priority defined? I can't seem to find it in the default dict.

**Comment by yanyiwu** [comment]
stop words does not works in cut api, it only works for (keyword) extract api.
