### ISSUE TITLE
能否取消对英文点 “.” 的分词？

### ISSUE THREAD

**Issue by colerape** [yanyiwu/nodejieba#92]
想直接搜索关键词 "www.baidu.com"，但是内容却会被分为: "."    "www"    "baidu"   "com"，以至于直接搜索的时候搜索不到。对于内容是: t.baidu.com;  a.baidu.com;  t.sohu.com;  a.sohu.com 的时候，由于点被分隔了，在存在大量域名的时候，基本查不到信息。

**Comment by yanyiwu** [comment]
英文的建议先特殊处理一下再进行中文分词，否则badcase很多。

**Comment by colerape** [comment]
谢谢，后来问题结局了。
