### ISSUE TITLE
centos6.7 node8.0 环境下安装失败

### ISSUE THREAD

**Issue by jaceechan** [yanyiwu/nodejieba#93]
报错信息如下:

Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /data/web/index.yeah18.cantonjs.cn/lib_next/node_modules/nodejieba
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@8.0.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/web/index.yeah18.cantonjs.cn/lib_next/node_modules/nodejieba/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/home/3went2/.node-gyp/8.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/home/3went2/.node-gyp/8.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/web/index.yeah18.cantonjs.cn/lib_next/node_modules/nodejieba',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/data/web/index.yeah18.cantonjs.cn/lib_next/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
In file included from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:21,
                 from /data/home/3went2/.node-gyp/8.0.0/include/node/node.h:63,
                 from ../lib/utils.h:4,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function 'virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)':
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function 'virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)':
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)':
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function '_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)':
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /data/home/3went2/.node-gyp/8.0.0/include/node/node.h:63,
                 from ../lib/utils.h:4,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: At global scope:
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:316: error: expected unqualified-id before 'using'
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:333: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:340: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:344: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::Eternal<T>::Eternal()':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:364: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:366: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'bool v8::Eternal<T>::IsEmpty() const':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:371: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:411: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::Global<T>::Global()':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:745: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::Global<T>::Global(v8::Global<T>&&)':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:770: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:782: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: At global scope:
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:808: error: expected unqualified-id before 'using'
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:1086: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:1092: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::RegisterState::RegisterState()':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:1627: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:3677: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: At global scope:
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:6366: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:6367: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:6380: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:6381: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In constructor 'v8::Isolate::CreateParams::CreateParams()':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:6403: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: At global scope:
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:7638: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:7655: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:7745: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:7746: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:7772: error: the default argument for parameter 0 of 'v8::SerializeInternalFieldsCallback::SerializeInternalFieldsCallback(v8::StartupData (*)(v8::Local<v8::Object>, int, void*), void*)' has not yet been parsed
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:7772: error: the default argument for parameter 1 of 'v8::SerializeInternalFieldsCallback::SerializeInternalFieldsCallback(v8::StartupData (*)(v8::Local<v8::Object>, int, void*), void*)' has not yet been parsed
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:8118: error: the default argument for parameter 0 of 'v8::DeserializeInternalFieldsCallback::DeserializeInternalFieldsCallback(void (*)(v8::Local<v8::Object>, int, v8::StartupData, void*), void*)' has not yet been parsed
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:8118: error: the default argument for parameter 1 of 'v8::DeserializeInternalFieldsCallback::DeserializeInternalFieldsCallback(void (*)(v8::Local<v8::Object>, int, v8::StartupData, void*), void*)' has not yet been parsed
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:8119: error: 'nullptr' was not declared in this scope
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
/data/home/3went2/.node-gyp/8.0.0/include/node/v8.h:8690: error: 'nullptr' was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before 'using'
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before 'using'
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:59: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:64: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:69: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:76: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:83: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:91: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:98: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:108: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:114: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:118: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:135: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:139: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:145: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:150: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:156: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:162: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:168: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:174: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:180: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:201: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:205: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:209: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:213: error: expected initializer before '<' token
../../nan/nan_maybe_43_inl.h:217: error: expected initializer before '<' token
../lib/index.cpp:24: error: expected '}' at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: 'void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: 'void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: 'void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: 'void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: 'void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: 'void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: 'void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: 'void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: 'void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: 'void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: 'void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: 'void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)' defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: 'void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)' defined but not used
make: *** [Release/obj.target/nodejieba/lib/index.o] Error 1
make: Leaving directory `/data/web/index.yeah18.cantonjs.cn/lib_next/node_modules/nodejieba/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 2.6.32-504.3.3.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/web/index.yeah18.cantonjs.cn/lib_next/node_modules/nodejieba
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

gcc版本：4.4.7

**Comment by yanyiwu** [comment]
安装的命令我看一下？理论上node8版本以上的，gcc必须是4.7以上的版本吧？因为需要支持c++11。可能是gcc版本的问题。

**Comment by jaceechan** [comment]
升级gcc到4.7后 问题解决  谢谢
