### ISSUE TITLE
大佬！怎么没有这个/build/Release/nodejieba.node 路径啊

### ISSUE THREAD

**Issue by songyang90525** [yanyiwu/nodejieba#96]

**Comment by yanyiwu** [comment]
巨佬，你要的应该是 ./build/Release/nodejieba.node  吧？少了一个点？

**Comment by songyang90525** [comment]
![3qk93 d2lv h oz7 jkf](https://user-images.githubusercontent.com/24603573/29238604-f7f6e872-7f6b-11e7-980d-e8a8a1022bfd.png)
或者说是没搞明白怎么用.首先按不上。然后 我把这个模块下载：
![12el 0 nvla97t 9ml58ji](https://user-images.githubusercontent.com/24603573/29238670-8928df44-7f6c-11e7-9ee3-8a9cbf6453cf.png)，
这个样子：
![5a75gmaj7u9yxqv6 sj ga](https://user-images.githubusercontent.com/24603573/29238768-d44574dc-7f6d-11e7-99eb-3c81d19bc4a4.png)



然后require( 'nodejieba' ) 后不能用  
然后我点开了 index.js,
![1 k7q 6 9rs1 9_d_ b8p3](https://user-images.githubusercontent.com/24603573/29238696-fae5eae6-7f6c-11e7-9c10-4dab7cde55a7.png)，怎么我下的模块少东西？没有“"/build/Release/nodejieba.node"”，大佬求助啊

**Comment by songyang90525** [comment]
今天翻了别的的问题，看了他们贴的代码，全局安装了node-gyp ，
![jxq9j 40f8j4n7cx mgedtq](https://user-images.githubusercontent.com/24603573/29350746-52e0644c-8292-11e7-9660-cd4685171c4a.png)
又尝试了下，貌似成功了，

**Comment by Willworkgogogo** [comment]
我也遇到了这个问题，能详细说下解决步骤吗@songyang90525
