### ISSUE TITLE
mixed english and chinese text?

### ISSUE THREAD

**Issue by dcsan** [yanyiwu/nodejieba#97]
Is there a way to get jieba to handle mixed text?
such as this:

> 罐身上的“SAP No. 1293164 ”

the english characters all get split into single letters:

> 罐 身上 的 “ S A P  N o . 1 2 9 3 1 6 4   ”

**Comment by HaoyuHu** [comment]
Same problem trapped me

**Comment by kenianbei** [comment]
For those still looking, it's:
`nodejieba.cut(text, false);`

**Comment by dcsan** [comment]
thanks! I had made a quick hack to check if inputs were completely english, but this mixed mode above had me stumped.

**Comment by tx0c** [comment]
> For those still looking, it's: `nodejieba.cut(text, false);`

what is that second parameter of `.cut`, is it well documented?

but it is still not working:

```js
> nodejieba.cut("南京市长江大桥 is a long bridge", false);
[
  '南京市', '长江大桥', ' ',
  'i',      's',        ' ',
  'a',      ' ',        'l',
  'o',      'n',        'g',
  ' ',      'b',        'r',
  'i',      'd',        'g',
  'e'
]
```
